version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: link_harvester
    container_name: link_harvester
    restart: always
    tty: true
    volumes:
      - .:/var/www/html
      #- "/mnt/d/laragon/www/interview/link-harvester:/var/www/html"
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.0.102
      - DB_PORT=3306
      - DB_DATABASE=link_harvester
      - DB_USERNAME=dbadmin
      - DB_PASSWORD=640087@m

  # configure the database service
  db:
    image: mysql:8.0.17
    container_name: link_harvester_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: dbadmin
      MYSQL_ROOT_PASSWORD: 640087@m
      MYSQL_PASSWORD: 640087@m
      MYSQL_DATABASE: link_harvester
      # SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
